service: serverless-midway-faas

provider:
  name: ''

functions:
  index:
    handler: index.handler
    events:
      - os: # os | oss | cos
          bucket: testoss
          events:
            - oss:ObjectCreated:PutObject
          filterPrefix: source/
          filterSuffix: .png
          role: 'acs:ram::1234567890:role/fc-invoke-test'
          version: 'LATEST' 

plugins:
  - serverless-midway-plugin

package:
  artifact: midwayFaas.zip
