service: serverless-midway-faas

provider:
  name: ''

functions:
  index:
    handler: index.handler
    events:
      - log:
          source: logstore1                               # required
          retryTime: 1                                    # default is 1
          interval: 20                                    # default is 30
          project: test                                   # required
          log: logstore                                   # required
          role: 'acs:ram::1234567890:role/fc-invoke-test' # option
          version: 'LATEST'                               # option

plugins:
  - serverless-midway-plugin

package:
  artifact: midwayFaas.zip
