service: serverless-midway-faas

provider:
  name: ''

functions:
  index:
    handler: index.handler
    events:
      - http:
          method: get

plugins:
  - serverless-midway-plugin

package:
  artifact: midwayFaas.zip
